name: nodejsCI build action
description: the sample Nodejs CI build action
runs: 
  using: "composite"
  steps:
  - uses: actions/setup-node@v1
    with:
      node-version: 10
  - name: Use Node.js 10      
    run: |
      npm ci 
      npm run build --if-present
    shell: bash
