name: nodejsCI build action
description: the sample Nodejs CI build action
runs: 
  using: "composite"
  steps:
  - uses: actions/setup-node@v1
    with:
      node-version: ${{ matrix.node-version }}
  - name: Use Node.js ${{ matrix.node-version }}      
    run: |
      npm ci 
      npm run build --if-present
    shell: bash
