name: Nodejs CI build action
description: the sample Nodejs CI build action
runs: 
  using: "composite"
  steps:
  - uses: actions/setup-node@v3
    with:
      node-version: 16
  - name: Use Node.js 16      
    run: |
      npm run build --if-present
    shell: bash
