name: module-two-workflow-NodejsCI
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      - name: NodejsCI build action
        uses: ./.github/workflows/actions/nodejsbuild
